# Generated by Django 5.2.1 on 2025-05-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='Loans',
            new_name='Loan',
        ),
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
